### ISSUE TITLE
allow_override not work for "project"

### ISSUE THREAD

**Issue by erickjx** [luismaia/redmine_email_fetcher#14] opened 2015-08-21 01:46 UTC
Hi, i test allow_override, but it don't work, the key word is "project", but always it set to default project, an example of body of mail is:

Project: B Project
Tracker: Support
Priority: Moderate
Status: New

But the ticket is created always in default project.

![navegador1](https://cloud.githubusercontent.com/assets/12073323/9399600/7952c3f2-477c-11e5-8ac7-ff22058a8456.png)

**Comment by octoquad** [comment] 2019-09-23 17:31
I know this ticket is old, but I think the problem is you are using the friendly name "B-Project" instead of the project identifier e.g. "b-project".

As per https://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails#Fetching-emails-from-a-POP3-server:
> The target project can be specified using the project option when receiving emails. This should be the identifier of the project and not the name. You can easily find the identifier in the URL.

If you no longer have this problem, please consider closing this issue.

Thanks

**Closed as completed** 2019-11-01 21:03 UTC
